package com.codegnan.MultiThreading;

/*
 * 								Getting and setting name if a thread.
 * 
 * 
 * Every thread in java has some name it may be provided explicitly-
 * by the programmer or automatically generated by the jvm.
 * 
 * Thread class defines the following methods to get and set name of a thread.
 * 1. public final String getName();
 * 2. public final void setname();
 * 
 * 
 * 
 */
public class GettingAndSettingOfAThread implements Runnable {

	@Override
	public void run() {
		
	}
	
	public static void main(String[] args) {
		System.out.println(Thread.currentThread().getName());
		GettingAndSettingOfAThread q =  new GettingAndSettingOfAThread();
		
		Thread thread = new Thread();
		System.out.println(thread.getName());
	}

}
